### ISSUE TITLE
Re-enable compiler features

### ISSUE THREAD

**Issue by camrein** [DafnyVSCode/ide-vscode#5]
The new [language server](https://github.com/DafnyVSCode/language-server-csharp) implementation does not support compiler related features yet. More precisely, the following features are unsupported as of now (see PR #4):

- [x] Show/Hide Counter-Example (F7 and F8) - Integrated with PR #9 
- [x] Compile (Ctrl + Shift + B) - Integrated with PR #10
- [x] Compile and Run (F5) - Integrated with PR #10
- [x] Compile with Arguments (F6) - Integrated with PR #10

These features are no longer exposed within the plugin and should be re-enabled as soon as they're supported.
